services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emotions_gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    env_file:
      - .env
    networks:
      - emotion-network

networks:
  emotion-network:
    external: true
